// <auto-generated />
using Comp229_301041266_Assign03.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Comp229_301041266_Assign03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Comp229_301041266_Assign03.Models.Favourite", b =>
                {
                    b.Property<int>("FavID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecID");

                    b.Property<string>("fvname");

                    b.HasKey("FavID");

                    b.ToTable("FavRecipe");
                });

            modelBuilder.Entity("Comp229_301041266_Assign03.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RecipeCategory")
                        .IsRequired();

                    b.Property<string>("RecipeCookTime")
                        .IsRequired();

                    b.Property<string>("RecipeIngredient")
                        .IsRequired();

                    b.Property<string>("RecipeIngredientQty");

                    b.Property<string>("RecipeIngredientUnit");

                    b.Property<string>("RecipeName")
                        .IsRequired();

                    b.Property<string>("RecipeNarrative")
                        .IsRequired();

                    b.Property<string>("RecipeNumberPortions")
                        .IsRequired();

                    b.HasKey("RecipeID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Comp229_301041266_Assign03.Models.ReviewRecipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecipeNumber");

                    b.Property<string>("ReviewContent")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
